"""Aider AI coding assistant integration.

Generates .aider.conf.yml configuration file for automatic context injection.
"""

from pathlib import Path
from typing import Optional

from idlergear.config import find_idlergear_root


def generate_aider_config() -> str:
    """Generate .aider.conf.yml configuration content.

    Returns:
        YAML configuration content for Aider
    """
    return """# .aider.conf.yml
# Generated by IdlerGear - AI-assisted development knowledge management
# Documentation: https://aider.chat/docs/config/options.html

# Commit settings
auto-commits: false
dirty-commits: false

# Context files (read-only)
# These files provide project context to Aider
read:
  - VISION.md          # Project vision and goals
  - AGENTS.md          # Agent instructions and conventions
  - CLAUDE.md          # Claude Code specific guidance
  - DEVELOPMENT.md     # Development practices
  - README.md          # Project overview

# Coding conventions
# IdlerGear follows these patterns
conventions: |
  ## IdlerGear Development Conventions

  ### CLI Commands
  - Use typer for CLI argument parsing
  - Use rich console for formatted output
  - Follow command naming: noun-verb pattern (e.g., task-create, note-list)

  ### Code Style
  - Follow PEP 8 for Python code
  - Use type hints for all public APIs
  - Document public functions with docstrings
  - Use ruff for linting and formatting

  ### Testing
  - Write tests for all new features
  - Use pytest for test framework
  - Place tests in tests/ directory
  - Name tests: test_<module>_<feature>.py

  ### MCP Tools
  - Follow MCP tool naming: idlergear_<category>_<action>
  - Return structured JSON from MCP tools
  - Include docstrings with parameter descriptions
  - Add tools to both list_tools() and call_tool()

  ### Knowledge Management
  - Use IdlerGear CLI commands, not markdown files
  - No TODO comments - create tasks instead
  - No NOTES.md files - use idlergear note create
  - Document architecture decisions as references

# Editor settings
edit-format: diff
show-diffs: true

# Code quality tools
lint-cmd: ruff check .
test-cmd: pytest

# Repository mapping
map-tokens: 1024
cache-prompts: true

# Git settings
git: true
gitignore: true
"""


def install_aider_config(project_path: Optional[Path] = None) -> str:
    """Install Aider configuration file (.aider.conf.yml).

    Args:
        project_path: Project directory (defaults to IdlerGear root)

    Returns:
        Action taken: 'created', 'updated', or 'unchanged'

    Raises:
        RuntimeError: If IdlerGear not initialized
    """
    if project_path is None:
        project_path = find_idlergear_root()
    if project_path is None:
        raise RuntimeError("IdlerGear not initialized. Run 'idlergear init' first.")

    config_path = project_path / ".aider.conf.yml"
    content = generate_aider_config()

    if not config_path.exists():
        config_path.write_text(content)
        return "created"
    else:
        existing_content = config_path.read_text()
        if existing_content != content:
            config_path.write_text(content)
            return "updated"
        else:
            return "unchanged"


def generate_aiderignore(project_path: Optional[Path] = None) -> str:
    """Generate .aiderignore file content.

    Args:
        project_path: Project directory (defaults to IdlerGear root)

    Returns:
        Action taken: 'created', 'updated', or 'unchanged'

    Raises:
        RuntimeError: If IdlerGear not initialized
    """
    if project_path is None:
        project_path = find_idlergear_root()
    if project_path is None:
        raise RuntimeError("IdlerGear not initialized. Run 'idlergear init' first.")

    aiderignore_path = project_path / ".aiderignore"

    content = """# IdlerGear internal directories
.idlergear/
.claude/hooks/
.claude/scripts/

# Build artifacts
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/
.cursor/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Dependencies
node_modules/

# Test coverage
.coverage
.pytest_cache/
htmlcov/

# Documentation builds
docs/_build/
site/
"""

    action = "unchanged"

    if not aiderignore_path.exists():
        aiderignore_path.write_text(content)
        action = "created"
    else:
        existing_content = aiderignore_path.read_text()
        if existing_content != content:
            # Append IdlerGear section if not present
            if ".idlergear/" not in existing_content:
                with open(aiderignore_path, "a") as f:
                    f.write("\n# IdlerGear internal directories\n")
                    f.write(".idlergear/\n")
                    f.write(".claude/hooks/\n")
                    f.write(".claude/scripts/\n")
                action = "updated"

    return action
