"""Shell script generator for IdlerGear-integrated development environments.

This module generates shell scripts that:
1. Set up the development environment (virtualenv, dependencies, etc.)
2. Register the process with the IdlerGear daemon
3. Stream logs to IdlerGear
4. Provide helpers for coordination
"""

from pathlib import Path
from typing import Any

from idlergear.config import find_idlergear_root


def generate_dev_script(
    script_name: str,
    command: str,
    *,
    venv_path: str | None = None,
    requirements: list[str] | None = None,
    env_vars: dict[str, str] | None = None,
    agent_name: str | None = None,
    agent_type: str = "dev-script",
    register_with_daemon: bool = True,
    stream_logs: bool = True,
    project_path: Path | None = None,
) -> str:
    """Generate a shell script for development environment setup.

    Args:
        script_name: Name for the script (used for agent registration)
        command: The main command to run
        venv_path: Path to virtualenv (if any)
        requirements: List of package requirements to install
        env_vars: Environment variables to set
        agent_name: Agent name (defaults to script_name)
        agent_type: Agent type for daemon registration
        register_with_daemon: Whether to register with daemon
        stream_logs: Whether to stream logs to daemon
        project_path: Project root path

    Returns:
        The generated shell script as a string
    """
    if project_path is None:
        project_path = find_idlergear_root()
    if project_path is None:
        raise RuntimeError("Not in an IdlerGear project")

    agent_name = agent_name or script_name
    requirements = requirements or []
    env_vars = env_vars or {}

    script = f"""#!/bin/bash
# Generated by IdlerGear
# Script: {script_name}
# Auto-registers with IdlerGear daemon for coordination

set -euo pipefail

# Configuration
SCRIPT_NAME="{script_name}"
AGENT_NAME="{agent_name}"
AGENT_TYPE="{agent_type}"
PROJECT_ROOT="{project_path}"
REGISTER_WITH_DAEMON={"true" if register_with_daemon else "false"}
STREAM_LOGS={"true" if stream_logs else "false"}

# Colors for output
GREEN='\\033[0;32m'
BLUE='\\033[0;34m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log() {{
    echo -e "${{BLUE}}[IdlerGear]${{NC}} $1"
}}

success() {{
    echo -e "${{GREEN}}[IdlerGear]${{NC}} $1"
}}

warn() {{
    echo -e "${{YELLOW}}[IdlerGear]${{NC}} $1"
}}

# Change to project directory
cd "$PROJECT_ROOT"

"""

    # Add virtualenv setup
    if venv_path:
        script += f"""
# Setup virtualenv
log "Setting up virtualenv at {venv_path}"
if [ ! -d "{venv_path}" ]; then
    python3 -m venv "{venv_path}"
    success "Created virtualenv"
fi

source "{venv_path}/bin/activate"
success "Activated virtualenv"

"""

    # Add requirements installation
    if requirements:
        script += """
# Install requirements
log "Installing dependencies..."
"""
        for req in requirements:
            script += f'pip install -q "{req}"\n'
        script += 'success "Dependencies installed"\n\n'

    # Add environment variables
    if env_vars:
        script += "# Set environment variables\n"
        for key, value in env_vars.items():
            script += f'export {key}="{value}"\n'
        script += "\n"

    # Add daemon registration
    if register_with_daemon:
        script += """
# Register with IdlerGear daemon
log "Registering with IdlerGear daemon..."

AGENT_ID=$(python3 -m idlergear.cli daemon register "$AGENT_NAME" \\
    --type "$AGENT_TYPE" \\
    --metadata "{{\\"script\\": \\"$SCRIPT_NAME\\", \\"pid\\": $$}}" 2>/dev/null || echo "")

if [ -n "$AGENT_ID" ]; then
    success "Registered as agent: $AGENT_ID"

    # Setup cleanup trap
    cleanup() {
        log "Unregistering from daemon..."
        python3 -m idlergear.cli daemon unregister "$AGENT_ID" 2>/dev/null || true
        success "Cleanup complete"
    }
    trap cleanup EXIT INT TERM
else
    warn "Could not register with daemon (is it running?)"
fi

"""

    # Add log streaming setup
    if stream_logs:
        script += """
# Setup log streaming
if [ -n "$AGENT_ID" ]; then
    # Named pipes for log streaming
    LOG_PIPE="/tmp/idlergear_${AGENT_ID}_log"
    mkfifo "$LOG_PIPE" 2>/dev/null || true

    # Background process to stream logs
    (
        while IFS= read -r line; do
            echo "$line"
            # Send to daemon
            python3 -m idlergear.cli daemon log "$AGENT_ID" "$line" 2>/dev/null || true
        done < "$LOG_PIPE"
    ) &
    LOG_STREAMER_PID=$!

    # Cleanup log pipe on exit
    cleanup_logs() {
        kill $LOG_STREAMER_PID 2>/dev/null || true
        rm -f "$LOG_PIPE"
    }
    trap cleanup_logs EXIT

    success "Log streaming enabled"
fi

"""

    # Add helper functions
    script += """
# Helper functions for IdlerGear coordination

idlergear_send() {
    # Send a message to other agents via daemon
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon send "$1" 2>/dev/null || true
    fi
}

idlergear_log() {
    # Log a message (shown locally and sent to daemon)
    log "$1"
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon log "$AGENT_ID" "$1" 2>/dev/null || true
    fi
}

idlergear_status() {
    # Update agent status
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon agent-status "$AGENT_ID" "$1" 2>/dev/null || true
    fi
}

"""

    # Add the main command
    script += f"""
# Main command
log "Starting: {command}"

{command}

success "Command completed successfully"
"""

    return script


def save_script(
    script_content: str,
    output_path: Path,
    make_executable: bool = True,
) -> Path:
    """Save a generated script to a file.

    Args:
        script_content: The script content
        output_path: Where to save it
        make_executable: Whether to chmod +x

    Returns:
        The path to the saved script
    """
    output_path.write_text(script_content)

    if make_executable:
        import stat

        output_path.chmod(output_path.stat().st_mode | stat.S_IEXEC)

    return output_path


def generate_script_from_template(
    template_name: str,
    script_name: str,
    **kwargs: Any,
) -> str:
    """Generate a script from a predefined template.

    Args:
        template_name: Template to use (pytest, django, flask, etc.)
        script_name: Name for the script
        **kwargs: Additional template parameters

    Returns:
        Generated script content
    """
    templates = {
        "pytest": {
            "command": "pytest -v",
            "requirements": ["pytest", "pytest-cov"],
        },
        "django-dev": {
            "command": "python manage.py runserver",
            "requirements": ["django"],
            "env_vars": {"DJANGO_SETTINGS_MODULE": "settings"},
        },
        "flask-dev": {
            "command": "flask run --debug",
            "requirements": ["flask"],
            "env_vars": {"FLASK_APP": "app.py", "FLASK_ENV": "development"},
        },
        "jupyter": {
            "command": "jupyter lab",
            "requirements": ["jupyterlab"],
        },
        "fastapi-dev": {
            "command": "uvicorn main:app --reload",
            "requirements": ["fastapi", "uvicorn"],
        },
    }

    if template_name not in templates:
        raise ValueError(f"Unknown template: {template_name}")

    template_config = templates[template_name]

    # Merge template config with kwargs
    config = {**template_config, **kwargs}

    return generate_dev_script(script_name, **config)
