#!/bin/bash
# Generated by IdlerGear
# Script: demo-app
# Auto-registers with IdlerGear daemon for coordination

set -euo pipefail

# Configuration
SCRIPT_NAME="demo-app"
AGENT_NAME="demo-app"
AGENT_TYPE="dev-script"
PROJECT_ROOT="/home/marc/Projects/idlergear"
REGISTER_WITH_DAEMON=true
STREAM_LOGS=true

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log() {
    echo -e "${BLUE}[IdlerGear]${NC} $1"
}

success() {
    echo -e "${GREEN}[IdlerGear]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[IdlerGear]${NC} $1"
}

# Change to project directory
cd "$PROJECT_ROOT"

# Set environment variables
export DEMO_MODE="true"


# Register with IdlerGear daemon
log "Registering with IdlerGear daemon..."

AGENT_ID=$(python3 -m idlergear.cli daemon register "$AGENT_NAME" \
    --type "$AGENT_TYPE" \
    --metadata "{{\"script\": \"$SCRIPT_NAME\", \"pid\": $$}}" 2>/dev/null || echo "")

if [ -n "$AGENT_ID" ]; then
    success "Registered as agent: $AGENT_ID"

    # Setup cleanup trap
    cleanup() {
        log "Unregistering from daemon..."
        python3 -m idlergear.cli daemon unregister "$AGENT_ID" 2>/dev/null || true
        success "Cleanup complete"
    }
    trap cleanup EXIT INT TERM
else
    warn "Could not register with daemon (is it running?)"
fi


# Setup log streaming
if [ -n "$AGENT_ID" ]; then
    # Named pipes for log streaming
    LOG_PIPE="/tmp/idlergear_${AGENT_ID}_log"
    mkfifo "$LOG_PIPE" 2>/dev/null || true

    # Background process to stream logs
    (
        while IFS= read -r line; do
            echo "$line"
            # Send to daemon
            python3 -m idlergear.cli daemon log "$AGENT_ID" "$line" 2>/dev/null || true
        done < "$LOG_PIPE"
    ) &
    LOG_STREAMER_PID=$!

    # Cleanup log pipe on exit
    cleanup_logs() {
        kill $LOG_STREAMER_PID 2>/dev/null || true
        rm -f "$LOG_PIPE"
    }
    trap cleanup_logs EXIT

    success "Log streaming enabled"
fi


# Helper functions for IdlerGear coordination

idlergear_send() {
    # Send a message to other agents via daemon
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon send "$1" 2>/dev/null || true
    fi
}

idlergear_log() {
    # Log a message (shown locally and sent to daemon)
    log "$1"
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon log "$AGENT_ID" "$1" 2>/dev/null || true
    fi
}

idlergear_status() {
    # Update agent status
    if [ -n "${AGENT_ID:-}" ]; then
        python3 -m idlergear.cli daemon agent-status "$AGENT_ID" "$1" 2>/dev/null || true
    fi
}


# Main command
log "Starting: echo 'Hello from demo app\!'; sleep 2; echo 'App running...'"

echo 'Hello from demo app\!'; sleep 2; echo 'App running...'

success "Command completed successfully"
